In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[3,-1,1], [2,-5,-3], [1,1,-3]])
Ab = np.hstack([A, np.array([[4,-17,0]]).T])
np.linalg.matrix_rank(A) == np.linalg.matrix_rank(Ab)

True

In [4]:
A = np.array([[2,-4,6], [1,-2,3], [3,-6,9]])
Ab = np.hstack([A, np.array([[1,-2,5]]).T])
ra = np.linalg.matrix_rank(A)
rab = np.linalg.matrix_rank(Ab)
if ra == rab and A.shape[1] == ra:
    print('One sulution')
elif ra == rab and A.shape[1] > rab:
    print('Infinity numner of solutions')
else:
    print('No solutions')

No solutions


In [5]:
A = np.array([[1,2,5], [3,1,-8],])
Ab = np.hstack([A, np.array([[4,-2]]).T])
ra = np.linalg.matrix_rank(A)
rab = np.linalg.matrix_rank(Ab)
if ra == rab and A.shape[1] == ra:
    print('One sulution')
elif ra == rab and A.shape[1] > rab:
    print('Infinity numner of solutions')
else:
    print('No solutions')

Infinity numner of solutions


In [6]:
A = np.array([[1,3,-2,4], [0,5,0,1], [0,0,3,0], [0,0,0,2]])
Ab = np.hstack([A, np.array([[3,2,4,1]]).T])
ra = np.linalg.matrix_rank(A)
rab = np.linalg.matrix_rank(Ab)
if ra == rab and A.shape[1] == ra:
    print('One sulution')
elif ra == rab and A.shape[1] > rab:
    print('Infinity numner of solutions')
else:
    print('No solutions')

One sulution


In [7]:
np.linalg.det(A)

30.000000000000004

In [8]:
np.linalg.solve(A, [3,2,4,1])

array([2.76666667, 0.3       , 1.33333333, 0.5       ])

PART II, task 5

In [9]:
coef_A = np.array([[11,7,5], [9,8,4], [2,1,3]])
B = np.array([-6,-5,1])
M, L, U = linalg.lu(coef_A)
print(L)
print(U)

[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


In [10]:
def solve_lu(coef_A: np.array, b: np.array) -> np.array:
    coef_shape = coef_A.shape
    L = np.eye(coef_A.shape[0])
    U = coef_A.copy().astype(np.float32)

    for j in range(L.shape[1]-1):
        for i in range(j+1, L.shape[1]):
            assert U[j,j] != 0, 'zero division'
            L[i,j] = U[i,j] / U[j,j]
            U[i,:] = U[i,:] - U[j,:] * L[i,j] 

    y = np.zeros((L.shape[1],))
    y[0] = b[0]
    for i in range(1,L.shape[1]):
        y[i] = b[i] - (L[i,:i]*y[:i]).sum()

    x = np.zeros((L.shape[0],))
    x[-1] = y[-1] / U[-1,-1]
    for i in range(1,L.shape[0]):
        x[-i-1] = (y[-i-1] - (U[-i-1,-i:]*x[-i:]).sum()) / U[-i-1,-i-1]
    x = np.round(x, 5)

    return x

solve_lu(coef_A, B)

array([-1., -0.,  1.])

In [11]:
from scipy.linalg import lu_factor, lu_solve
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
b = np.array([1, 1, 1, 1])
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
x

array([ 0.05154639, -0.08247423,  0.08247423,  0.09278351])

In [12]:
solve_lu(A,b)

array([ 0.05155, -0.08247,  0.08247,  0.09278])

In [13]:
lu, piv = lu_factor(coef_A)
lu_solve((lu, piv), B)

array([-1.,  0.,  1.])