In [ ]:
import numpy as np

In [ ]:
def def_mtx(X: np.array, Y: np.array):
    if X.shape[1] == Y.shape[0]:
        print(f'{X.dot(Y).shape}')
    else:
        print(f'Not defined: {X.shape}, {Y.shape}')

In [ ]:
# task 1
# assert num_cols_A == num_rows_B
for point, shapeA, shapeB in zip(['a', 'b', 'c', 'd'], [(4,2), (2,5), (8,3), (4,4)], [(4,2), (5,3), (3,8), (4,4)]):
    print(f'{point})')
    A = np.ones(shapeA)
    B = np.ones(shapeB)
    def_mtx(A,B)
    def_mtx(B,A)
    print('-'*20)

a)
Not defined: (4, 2), (4, 2)
Not defined: (4, 2), (4, 2)
--------------------
b)
(2, 3)
Not defined: (5, 3), (2, 5)
--------------------
c)
(8, 8)
(3, 3)
--------------------
d)
(4, 4)
(4, 4)
--------------------


In [ ]:
# task 2
A = np.array([[1,-2], [3,0]])
B = np.array([[4,-1], [0,5]])
print(f'Sum:\n {A+B}')
print(f'Prod:\n {A.dot(B)}')

Sum:
 [[ 5 -3]
 [ 3  5]]
Prod:
 [[  4 -11]
 [ 12  -3]]


In [ ]:
# task 3
A = np.array([[1,7], [3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

In [ ]:
# task 4
A = np.array([[4,1], [5,-2], [2,3]])
print(f'A @ A_T:\n {A.dot(A.T)}')
print(f'A_T @ A:\n {A.T.dot(A)}')

A @ A_T:
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
A_T @ A:
 [[45  0]
 [ 0 14]]


In [ ]:
# task 5
from itertools import product

def mul_matrix_fast(A: list, B: list) -> list:
    assert len(A[0]) == len(B), 'number of cols A should be equal rows B'
    C = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i, j, k in product(range(len(A)), range(len(B[0])), range(len(B))):
        C[i][j] += A[i][k] * B[k][j]
    return C

def mul_matrix(A: list, B: list) -> list:
    assert len(A[0]) == len(B), 'number of cols A should be equal rows B'
    C = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k] * B[k][j]
    return C

A = [[1,2,3,4],
     [4,3,2,1],
     [0,3,2,1]]
B = [[1,3],
     [2,4],
     [5,1],
     [0,2]]
print(*mul_matrix(A,B), sep='\n')
print('-'*10)
print(*mul_matrix_fast(A,B), sep='\n')
print('-'*10)
np.dot(np.array(A), np.array(B)) # check

[20, 22]
[20, 28]
[16, 16]
----------
[20, 22]
[20, 28]
[16, 16]
----------


array([[20, 22],
       [20, 28],
       [16, 16]])

In [ ]:
# PART 2
# task 1
x = 5
A = np.array([[np.sin(x), -np.cos(x)],
              [np.cos(x), np.sin(x)]])
np.linalg.det(A)

1.0

In [ ]:
A = np.array([[4,2,3],
              [0,5,1],
              [0,0,9]])
np.linalg.det(A)

180.0

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np.linalg.det(A)

0.0

In [ ]:
# task 2

In [ ]:
# task 3
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(A)

0.0

In [ ]:
# task 4
A = np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(A)

2

In [ ]:
A = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
np.linalg.matrix_rank(A)

3